/**
 * News Service — Server-side data access.
 */

export interface NewsArticle {
    id: string; title: string; summary: string; content: string[];
    date: string; source: string; category: string; impact?: string;
}

const mockNews: NewsArticle[] = [
    { id: "news-rbi-1", title: "RBI Holds Repo Rate at 6.5%, Maintains 'Withdrawal of Accommodation' Stance", summary: "The Monetary Policy Committee voted to keep interest rates unchanged to ensure inflation aligns with the target.", content: ["The Reserve Bank of India (RBI) Governor Shaktikanta Das announced today that the Monetary Policy Committee (MPC) has decided to keep the repo rate unchanged at 6.5%.", "The decision was driven by the need to balance economic growth with price stability.", "Analysts at major Indian brokerages had largely expected this outcome.", "Bank stocks showed a mixed reaction, with HDFC Bank and ICICI Bank ending the session slightly lower."], date: "2026-03-15T11:30:00Z", source: "Economic Times India", category: "Economy", impact: 'High' },
    { id: "news-sebi-t0-2", title: "SEBI Introduces T+0 Settlement for Select Stocks in Indian Markets", summary: "The market regulator is pushing for same-day settlement to enhance liquidity and efficiency.", content: ["The Securities and Exchange Board of India (SEBI) has officially kicked off the pilot project for T+0 settlement cycles for a limited universe of 25 stocks.", "This move follows the successful transition to T+1 settlement last year.", "Regulators believe this will unlock collateral and significantly reduce credit risk.", "The initial pilot includes blue-chip stocks like Reliance, TCS, and ITC."], date: "2026-03-14T09:00:00Z", source: "Mint", category: "Markets", impact: 'High' },
    { id: "news-tech-ai-3", title: "India's Tech Giants Invest Heavily in Sovereign AI Infrastructure", summary: "TCS and Infosys lead the charge in establishing localized LLMs and data sovereign compute clusters.", content: ["Leading Indian IT services firms are pivoting their strategies toward building 'Sovereign AI' solutions.", "TCS recently announced a multi-crore investment into a new center of excellence focused on developing LLMs trained on Indic languages.", "This shift comes as the Indian government continues to emphasize data localization.", "Industry experts believe this could open up massive new revenue streams."], date: "2026-03-13T10:15:00Z", source: "The Tech Pulse", category: "Tech", impact: 'Medium' },
    { id: "news-budget-expect-4", title: "Markets Rally on Pre-Budget Optimism and Capital Expenditure Hopes", summary: "Nifty 50 touches new lifetime highs as investors anticipate continued focus on infrastructure.", content: ["The Indian equity indices reached new milestones today, with the Nifty 50 crossing the critical 22,500 mark.", "The rally is largely fueled by expectations of continued aggressive capital expenditure.", "Domestic institutional investors (DIIs) have been strong buyers.", "Construction and Metal stocks were the top gainers."], date: "2026-03-12T15:45:00Z", source: "Business Standard", category: "Markets", impact: 'Medium' },
    { id: "news-gold-5", title: "Gold Prices Surge to Record Highs Amid Global Economic Uncertainty", summary: "Spot gold hit a new all-time high as investors seek safety in the precious metal.", content: ["Gold prices have broken through major resistance levels today, reaching a record high of over ₹75,000 per 10 grams.", "The surge is attributed to geopolitical tensions and expectations of central bank rate cuts.", "Domestic jewelry demand has seen a temporary dip but investment demand stays robust.", "Financial advisors suggest staggered investments."], date: "2026-03-11T08:30:00Z", source: "Bloomberg Quint", category: "Crypto", impact: 'High' },
    { id: "news-oil-6", title: "Crude Oil Stabilizes as Global Demand Outlook Projects Growth", summary: "Oil prices held steady today as OPEC+ maintains its production cut strategy.", content: ["Brent crude oil futures settled at $85 per barrel today.", "OPEC+ leaders have reiterated their commitment to maintaining production ceilings.", "For the Indian economy, these levels are manageable but further upside could weigh on the current account deficit.", "Energy sector stocks, particularly ONGC, have seen positive momentum."], date: "2026-03-10T14:20:00Z", source: "Reuters Business", category: "Geopolitics", impact: 'Medium' }
];

export const getAllNews = () => mockNews;
export const getNewsById = (id: string) => mockNews.find(n => n.id === id);
